#!/bin/bash

#####Color Codes#####
RED='\033[01;31m'
GREEN='\033[01;32m'
YELLOW='\033[01;33m'
PURPLE='\033[01;35m'
CYAN='\033[01;36m'
#####################

clear
echo -e ${CYAN}
figlet "MariaDB Cracker"
echo -e ${RED}
figlet 'Coded by Decrypt3r' -f digital
echo
echo
echo  -e "\033[33;5mYou are going to reset Mariadb Password\033[0m"
sleep 2
echo -e ${GREEN}
read -p "Are you sure, you want to reset the password?[yes/no]:" a
case $a in
yes)
	python marcrackk/crack.py
	;;

y)
	python marcrackk/crack.py
	;;

no)
	echo "Thank you for using Marcrack"
	;;

n)
	echo "Thank you for using Marcrack"
	;;

*)
	echo -e ${RED} "Invalid Option"
	;;

esac
